# Generated by Django 3.0.7 on 2020-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Описание картинки'),
        ),
    ]
